### PR TITLE
Added ATREAY profile

### PR DESCRIPTION
**Pull request by ATREAY**

### CODE REVIEW

**Comment by anthonyliriano** [comment]
@ATREAY did you submit the PR via Gibwork? https://app.gib.work/

**Comment by ATREAY** [comment]
I attempted to submit the pull request using Gibwork but encountered an error, leading to redirection to the following link: https://app.gib.work/r/WcRn5jGP/web3-devs?error
Consequently, I proceeded to create the pull request directly in this repository.

**Comment by ATREAY** [comment]
After closing this pull request, I attempted to submit it again, but it was redirected to the same error link.

**Comment by anthonyliriano** [comment]
Hi @ATREAY, sorry for the confusion but you you need to make your commit to the gib-bounty-vbKji branch, assigned to you. https://github.com/ATREAY/web3-devs/tree/gib-bounty-vbKji 

Jump on the discord if you're still encountering any issues  https://discord.gg/wZysX2PW

**Comment by ATREAY** [comment]
It is giving invite expired error.

**Comment by anthonyliriano** [comment]
@ATREAY strange try this - https://discord.gg/N3kgPRadKq

**Pull request closed without merging**
